[file]
traffic = ./data/GLA/flowgla.npz
meta = ./data/GLA/gla_meta.csv
adj = ./data/GLA/adj.npy
model = ./cpt/gla_adaptive_stage2_model
log = ./log/gla_adaptive_stage2_log
result = ./results/gla_adaptive_stage2_result.json
prediction = ./results/gla_adaptive_stage2_prediction.npz

[data]
input_len = 12
output_len = 12
train_ratio = 0.6
val_ratio = 0.2
test_ratio = 0.2

[train]
cuda = 0
max_epoch = 5
batch_size = 16
learning_rate = 0.001
weight_decay = 0.0001
seed = 111

[param]
factors = 32
layers = 5
tps = 12
tpn = 1
recur = 11
sps = 2
spn = 2048
nodes = 3834
tod = 96
dow = 7
id = 64
nd = 32
td = 32
dd = 32
merge_tau = 0.45
