[file]
traffic = ./data/SD/flowsd.npz
meta = ./data/SD/sd_meta.csv
adj = ./data/SD/adj.npy
model = ./cpt/sd_adaptive_stage2_model
log = ./log/sd_adaptive_stage2_log
result = ./results/sd_adaptive_stage2_result.json
pretrained = ./cpt/sd_adaptive_finetune_model

[data]
input_len = 12
output_len = 12
train_ratio = 0.6
val_ratio = 0.2
test_ratio = 0.2

[train]
cuda = 0
max_epoch = 5
batch_size = 16
learning_rate = 0.0001
weight_decay = 0.0
seed = 4096

[param]
factors = 32
layers = 5
tps = 12
tpn = 1
recur = 9
sps = 2
spn = 512
nodes = 716
tod = 96
dow = 7
id = 64
nd = 64
td = 32
dd = 32
merge_tau = 0.45
